[package]
name = "networking"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.36.0", features = ["net"] }

rmp = "0.8.12"
rmp-serde = "1.1.2"
